FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements-modules.txt ./
COPY vendor ./vendor
RUN pip install -r requirements.txt
RUN saltshack-build --check

COPY . .

CMD ["./scripts/start_celery.sh"]
