FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl lsb-release \
    && rm -rf /var/lib/apt/lists/*

# Install nodejs, npm
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y --no-install-recommends nodejs npm \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

COPY requirements.txt requirements-modules.txt ./
COPY vendor ./vendor
RUN pip install -r requirements.txt

COPY . .
RUN npm run modules:frontend && npm run build


CMD ["/app/scripts/run_dev_env.sh"]
