"""Create a safe, writable Pywikibot configuration for framework processes.

Containers do not always have a conventional home directory.  The resolver tries
operator configuration first and then controlled fallbacks.  Generated files are
marked and updated atomically; an unmarked user-managed configuration is never
overwritten.
"""

from __future__ import annotations

import os
from pathlib import Path

_DEFAULT_BOT_USERNAME = "Chuckbot"
_GENERATED_CONFIG_MARKER = "# Generated by Chuck the Buckbot Framework."


def _desired_user_config(bot_username: str) -> str:
    """Return a minimal but OAuth-capable Pywikibot user-config.py."""
    return (
        f"{_GENERATED_CONFIG_MARKER}\n"
        "import os\n\n"
        "family = 'commons'\n"
        "mylang = 'commons'\n"
        f"usernames['commons']['commons'] = '{bot_username}'\n\n"
        f"usernames['commons']['*'] = '{bot_username}'\n"
        f"usernames['wikipedia']['en'] = '{bot_username}'\n"
        f"usernames['wikipedia']['*'] = '{bot_username}'\n\n"
        "if all(\n"
        "    os.getenv(name)\n"
        "    for name in ('CONSUMER_TOKEN', 'CONSUMER_SECRET', 'ACCESS_TOKEN', 'ACCESS_SECRET')\n"
        "):\n"
        "    _oauth = (\n"
        "        os.getenv('CONSUMER_TOKEN'),\n"
        "        os.getenv('CONSUMER_SECRET'),\n"
        "        os.getenv('ACCESS_TOKEN'),\n"
        "        os.getenv('ACCESS_SECRET'),\n"
        "    )\n"
        "    authenticate['commons.wikimedia.org'] = _oauth\n"
        "    authenticate['en.wikipedia.org'] = _oauth\n"
        "    for _host in (\n"
        "        '*.wikipedia.org',\n"
        "        '*.wikimedia.org',\n"
        "        '*.wikidata.org',\n"
        "        '*.wiktionary.org',\n"
        "        '*.wikibooks.org',\n"
        "        '*.wikinews.org',\n"
        "        '*.wikiquote.org',\n"
        "        '*.wikisource.org',\n"
        "        '*.wikiversity.org',\n"
        "        '*.wikivoyage.org',\n"
        "        '*.mediawiki.org',\n"
        "    ):\n"
        "        authenticate[_host] = _oauth\n"
    )


def _write_generated_config(config_file: Path, desired: str) -> None:
    """Atomically replace a framework-owned Pywikibot config."""
    temporary = config_file.with_name(f".{config_file.name}.{os.getpid()}.tmp")
    try:
        temporary.write_text(desired, encoding="utf-8")
        temporary.replace(config_file)
    finally:
        temporary.unlink(missing_ok=True)


def resolve_pywikibot_dir() -> Path:
    """Return a writable directory for Pywikibot config files."""
    candidates: list[Path] = []

    env_dir = os.environ.get("PYWIKIBOT_DIR")
    if env_dir:
        candidates.append(Path(env_dir))

    home = os.environ.get("HOME")
    if home and home != "/":
        candidates.append(Path(home) / ".pywikibot")

    candidates.append(Path("/workspace") / ".pywikibot")
    candidates.append(Path("/tmp") / f".pywikibot-{os.getuid()}")

    # Probe actual file writes rather than trusting directory mode bits, which
    # can be misleading on container mounts and Toolforge network filesystems.
    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=True)
            probe = candidate / ".chuckbot-write-test"
            probe.write_text("", encoding="utf-8")
            probe.unlink(missing_ok=True)
            return candidate
        except OSError:
            continue

    raise RuntimeError("No writable directory available for PYWIKIBOT_DIR")


def ensure_pywikibot_env(
    *,
    bot_username: str = _DEFAULT_BOT_USERNAME,
    strict: bool = True,
) -> Path | None:
    """Set PYWIKIBOT_DIR and ensure a minimal user-config.py exists.

    When strict is False, errors are swallowed and None is returned.
    """
    try:
        pywikibot_home = resolve_pywikibot_dir()
        os.environ["PYWIKIBOT_DIR"] = str(pywikibot_home)

        config_file = pywikibot_home / "user-config.py"
        desired = _desired_user_config(bot_username)

        if not config_file.exists():
            _write_generated_config(config_file, desired)
        else:
            current = config_file.read_text(encoding="utf-8")
            # Never overwrite a user-managed Pywikibot configuration. Framework
            # configs carry an explicit marker so upgrades remain safe.
            if _GENERATED_CONFIG_MARKER in current and current != desired:
                _write_generated_config(config_file, desired)

        return pywikibot_home
    except Exception:
        if strict:
            raise
        return None
