name = "rollback"
repo = "https://github.com/chuckthebuck/bucksaltbot2"
entry_point = "modules.rollback.blueprint"
ui = true
buildpacks = ["heroku/python"]
redis_namespace = "rollback"
title = "Rollback"
