#!/usr/bin/env python3
"""Generate the external-module requirements from enabled vendored modules.

The framework deploys module source snapshots from ``vendor/modules``.  Keeping
their local paths generated avoids a manual list that can drift when a module
is added, removed, or renamed.
"""

from __future__ import annotations

import argparse
from pathlib import Path


HEADER = """# Optional Chuck the Buckbot Framework modules.
#
# This file is generated by scripts/update-module-requirements.py. Do not edit
# the paths by hand; update enabled-modules.txt and the vendored module instead.
# Toolforge Build Service installs these local snapshots and never fetches a
# module repository while deploying.
"""


def enabled_module_names(path: Path) -> list[str]:
    """Read enabled module names in declaration order, ignoring comments."""
    names: list[str] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        name = raw_line.split("#", 1)[0].strip()
        if name:
            names.append(name)
    return names


def render_requirements(root: Path) -> str:
    """Return requirements for enabled modules that are vendored packages."""
    paths: list[str] = []
    for name in enabled_module_names(root / "enabled-modules.txt"):
        module_dir = root / "vendor" / "modules" / name
        if not module_dir.is_dir():
            continue
        pyproject = module_dir / "pyproject.toml"
        if not pyproject.is_file():
            raise SystemExit(f"Vendored module {name!r} is missing {pyproject}")
        paths.append(f"./vendor/modules/{name}")
    return HEADER + "\n".join(paths) + "\n"


def main() -> int:
    """Write or verify the generated requirements file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail instead of writing a stale file"
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    destination = root / "requirements-modules.txt"
    expected = render_requirements(root)
    actual = destination.read_text(encoding="utf-8") if destination.exists() else ""

    if actual == expected:
        print("requirements-modules.txt is up to date")
        return 0
    if args.check:
        print(
            "requirements-modules.txt is stale; run "
            "python3 scripts/update-module-requirements.py",
        )
        return 1

    destination.write_text(expected, encoding="utf-8")
    print("updated requirements-modules.txt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
